const properties = [
  {id:"yona",name:"YONA",location:"Vista Grande Subdivision, Talisay City, Cebu",price:"₱29,000,000",description:"A refined three-level residence with generous family spaces, layered terraces, and contemporary tropical character.",images:["assets/houses/YONA House/1.jpg","assets/houses/YONA House/2.jpg"],specs:[["Type","3-level residence"],["Beds","4"],["Baths","4"],["Lot area","183 sqm"]]},
  {id:"sagada",name:"SAGADA",location:"Vista Grande Subdivision, Talisay City, Cebu",price:"₱48,000,000",description:"A private architectural residence with multiple living levels, a swimming pool, elevator, and expansive indoor-outdoor spaces.",images:["assets/houses/SAGADA House/1.jpg","assets/houses/SAGADA House/2.jpg"],specs:[["Type","Luxury residence"],["Beds","5"],["Baths","5"],["Lot area","271.99 sqm"]]},
  {id:"cliffside",name:"Cliffside House",location:"Busay, Cebu City",price:"₱31,200,000",description:"A private hillside home framed by open skies and expansive views of the city below.",images:["https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1600&q=85","https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1000&q=85","https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1000&q=85"],specs:[["Type","Residence"],["Beds","5"],["Baths","4"],["Floor area","310 sqm"]]},
  {id:"verona",name:"The Verona",location:"Lapu-Lapu City",price:"₱16,900,000",description:"A serene, light-filled home for slow mornings, long lunches, and life well lived.",images:["https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1600&q=85","https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?auto=format&fit=crop&w=1000&q=85","https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1000&q=85"],specs:[["Type","Residence"],["Beds","3"],["Baths","3"],["Floor area","165 sqm"]]},
  {id:"mira",name:"Mira Gardens",location:"Talamban, Cebu City",price:"₱21,400,000",description:"A garden-led residence balancing privacy, generous proportions, and an effortless indoor-outdoor rhythm.",images:["https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1600&q=85","https://images.unsplash.com/photo-1600566753051-f0b89df2dd90?auto=format&fit=crop&w=1000&q=85","https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1000&q=85"],specs:[["Type","Residence"],["Beds","4"],["Baths","3"],["Floor area","220 sqm"]]}
];
let activeIndex=0, heroTimer;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const heroMedia=$("#hero-media"), title=$("#hero-title"), description=$("#hero-description"), progress=$("#hero-progress");
function titleMarkup(name){return `${name.split(" ").map(word=>`<span class="hero-word">${word}</span>`).join(" ")}<br /><em class="hero-word hero-word-em">Residence</em>`}
function setHero(index, animate=true){activeIndex=(index+properties.length)%properties.length;const p=properties[activeIndex];if(animate)heroMedia.classList.add("is-changing");setTimeout(()=>{heroMedia.style.backgroundImage=`url("${p.images[0]}")`;title.innerHTML=titleMarkup(p.name);description.textContent=p.description;$("#hero-location").textContent=p.location;$("#hero-index").textContent=String(activeIndex+1).padStart(2,"0");progress.style.width=`${((activeIndex+1)/properties.length)*100}%`;title.classList.remove("text-pop");description.classList.remove("text-pop");document.querySelector(".hero-copy .button").classList.remove("text-pop");requestAnimationFrame(()=>{title.classList.add("text-pop");description.classList.add("text-pop");document.querySelector(".hero-copy .button").classList.add("text-pop")});heroMedia.classList.remove("is-changing")},animate?360:0);resetTimer()}
function resetTimer(){clearInterval(heroTimer);heroTimer=setInterval(()=>setHero(activeIndex+1),6500)}
function openDetail(index){activeIndex=index;const p=properties[index];const view=$("#detail-view");view.setAttribute("aria-hidden","false");$("#detail-title").innerHTML=`${p.name}<br /><em>Residence</em>`;$("#detail-location").textContent=p.location;$("#detail-description").textContent=p.description;$("#detail-price").textContent=p.price;$("#detail-index").textContent=`${String(index+1).padStart(2,"0")} / 05`;$("#detail-specs").innerHTML=p.specs.map(s=>`<div><span>${s[0]}</span><strong>${s[1]}</strong></div>`).join("");$("#gallery-thumbs").innerHTML=p.images.map((image,i)=>`<button class="${i===0?"active":""}" style="background-image:url('${image}')" aria-label="View image ${i+1}"></button>`).join("");setGallery(p.images[0]);$$(".gallery-thumbs button").forEach((button,i)=>button.addEventListener("click",()=>{setGallery(p.images[i]);$$(".gallery-thumbs button").forEach(b=>b.classList.remove("active"));button.classList.add("active")}));view.scrollIntoView({behavior:"smooth",block:"start"});$("#property-select").value=p.id;$("#selected-property").textContent=p.name}
function setGallery(image){const imageBox=$("#detail-main-image");imageBox.style.opacity=0;setTimeout(()=>{imageBox.style.backgroundImage=`url("${image}")`;imageBox.style.opacity=1},160)}
function renderCards(){const track=$("#residence-track");track.innerHTML=properties.map((p,i)=>`<article class="res-card" data-index="${i}"><div class="res-image" style="background-image:url('${p.images[0]}')"></div><div class="res-meta"><h3>${p.name}</h3><strong>${p.price}</strong><p>${p.location}</p></div></article>`).join("");$$(".res-card").forEach(card=>card.addEventListener("click",()=>openDetail(Number(card.dataset.index))))}
function renderSelect(){const select=$("#property-select");select.innerHTML=`<option value="">General inquiry</option>`+properties.map(p=>`<option value="${p.id}">${p.name}</option>`).join("");select.addEventListener("change",()=>{$("#selected-property").textContent=select.value?properties.find(p=>p.id===select.value).name:"General inquiry"})}
setHero(0,false);renderCards();renderSelect();
$("#hero-prev").addEventListener("click",()=>setHero(activeIndex-1));$("#hero-next").addEventListener("click",()=>setHero(activeIndex+1));$("#hero-explore").addEventListener("click",()=>openDetail(activeIndex));$("#close-detail").addEventListener("click",()=>{$("#detail-view").setAttribute("aria-hidden","true");$("#home").scrollIntoView({behavior:"smooth"})});$(".interest-button").addEventListener("click",()=>{$("#detail-view").setAttribute("aria-hidden","true");$("#contact").scrollIntoView({behavior:"smooth",block:"start"});setTimeout(()=>$("#inquiry-form input[name=\"name\"]").focus(),500)});
$("#res-prev").addEventListener("click",()=>$("#residence-track").scrollBy({left:-430,behavior:"smooth"}));$("#res-next").addEventListener("click",()=>$("#residence-track").scrollBy({left:430,behavior:"smooth"}));
$("#inquiry-form").addEventListener("submit",e=>{e.preventDefault();const form=e.currentTarget;if(!form.checkValidity()){form.reportValidity();return}$("#form-status").textContent="Thank you — we’ll be in touch within one business day.";form.reset();$("#selected-property").textContent="General inquiry"});
const header=$("#site-header");window.addEventListener("scroll",()=>header.classList.toggle("scrolled",window.scrollY>40),{passive:true});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)entry.target.classList.add("visible")}),{threshold:.15});$$(".reveal").forEach(el=>observer.observe(el));
const toggle=$("#menu-toggle"),mobile=$("#mobile-nav");toggle.addEventListener("click",()=>{const open=mobile.classList.toggle("open");toggle.setAttribute("aria-expanded",open)});$$(".mobile-nav a").forEach(link=>link.addEventListener("click",()=>mobile.classList.remove("open")));
